/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#474646",
        "outline": "#8f9194",
        "surface": "#141313",
        "surface-container-highest": "#353434",
        "on-tertiary": "#303030",
        "secondary-container": "#4a4949",
        "surface-variant": "#353434",
        "on-primary": "#2f3132",
        "surface-tint": "#c6c6c8",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#3a3939",
        "secondary-fixed": "#e5e2e1",
        "inverse-primary": "#5d5e60",
        "outline-variant": "#44474a",
        "primary": "#ffffff",
        "on-tertiary-container": "#656464",
        "surface-container-low": "#1c1b1b",
        "primary-container": "#e2e2e4",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c6",
        "secondary-fixed-dim": "#c9c6c5",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c5c7c9",
        "on-secondary": "#313030",
        "inverse-on-surface": "#313030",
        "background": "#141313",
        "error-container": "#93000a",
        "on-primary-container": "#636466",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-fixed": "#1a1c1d",
        "on-primary-fixed-variant": "#454749",
        "on-error": "#690005",
        "tertiary-fixed": "#e4e2e1",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "secondary": "#c9c6c5",
        "on-tertiary-fixed-variant": "#474747",
        "tertiary": "#ffffff",
        "error": "#ffb4ab",
        "surface-dim": "#141313",
        "primary-fixed-dim": "#c6c6c8",
        "surface-container": "#201f1f",
        "primary-fixed": "#e2e2e4",
        "on-secondary-container": "#bab8b7",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-container": "#e4e2e1"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        base: "8px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "mono-technical": ["Geist"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "display-lg": ["Hanken Grotesk"],
        "label-caps": ["Geist"]
      },
      fontSize: {
        "mono-technical": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["44px", { lineHeight: "48px", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
