package com.smartcart.config;

import com.smartcart.entity.Product;
import com.smartcart.entity.Role;
import com.smartcart.entity.User;
import com.smartcart.repository.ProductRepository;
import com.smartcart.repository.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Optional;

@Component
public class DatabaseSeeder implements CommandLineRunner {

    private final ProductRepository productRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public DatabaseSeeder(ProductRepository productRepository, UserRepository userRepository,
            PasswordEncoder passwordEncoder) {
        this.productRepository = productRepository;
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(String... args) {
        seedUsers();
        seedProducts();
    }

    private void seedUsers() {
        if (userRepository.count() == 0) {
            User user = new User();
            user.setName("John Doe");
            user.setEmail("user@technest.com");
            user.setPassword(passwordEncoder.encode("password123"));
            user.setRole(Role.USER);
            userRepository.save(user);

            User admin = new User();
            admin.setName("Admin User");
            admin.setEmail("admin@technest.com");
            admin.setPassword(passwordEncoder.encode("admin123"));
            admin.setRole(Role.ADMIN);
            userRepository.save(admin);
        }
    }

    private void seedProducts() {
        if (productRepository.count() < 40) {
            System.out.println("Clearing old product catalog to build multi-brand tech ecosystem...");
            productRepository.deleteAll();
        }

        seedProduct("Nova Sonic ANC", "SonicX ANC Pro", "SonicX", "Premium wireless headphones engineered for immersive audio, all-day comfort, and intelligent noise cancellation. | Specs: Bluetooth Version: 5.3, Battery Life: 40 Hours, Driver Size: 40mm, Noise Cancellation: Active ANC (45dB), Charging Type: USB-C Quick Charge", "9999.00", "9999.00", "0", "Audio", "/images/products/audio gear/hp 1.jpg", 4.6, 809, 126, "Within a week", false, false);
        seedProduct("Nova Echo Air", "EchoTech Air", "EchoTech", "Ultra-lightweight wireless earbuds designed for active lifestyles and crystal clear calls. | Specs: Bluetooth Version: 5.4, Battery Life: 32 Hours, Driver Size: 11mm, Noise Cancellation: Hybrid ANC (40dB), Charging Type: USB-C", "3599.00", "4999.00", "28", "Audio", "/images/products/audio gear/earbuds.jpg", 4.0, 655, 29, "3-5 Days", false, false);
        seedProduct("Nova Pulse ANC", "Pulse Audio ANC", "Pulse Audio", "Over-ear hybrid active noise cancelling headphones for your daily commute and deep focus. | Specs: Bluetooth Version: 5.3, Battery Life: 50 Hours, Driver Size: 40mm, Noise Cancellation: Hybrid ANC (43dB), Charging Type: USB-C Quick Charge", "5039.00", "7999.00", "37", "Audio", "/images/products/audio gear/hp2.jpg", 4.0, 1120, 148, "2 Days", false, true);
        seedProduct("Nova Resonance Pro", "Resonance Pro Studio", "Resonance", "Flagship audiophile over-ear headphones with custom hybrid dynamic drivers and premium memory foam cushions. | Specs: Bluetooth Version: 5.3, Battery Life: 45 Hours, Driver Size: 45mm, Noise Cancellation: Hybrid ANC (48dB), Charging Type: Qi Wireless + USB-C", "14999.00", "14999.00", "0", "Audio", "/images/products/audio gear/hp3.jpg", 4.3, 209, 182, "Tomorrow", false, true);
        seedProduct("Nova Wave Studio", "SonicX Wave Studio", "SonicX", "High-resolution reference studio headphones designed for professional audio mixing and mastering. | Specs: Bluetooth Version: Wired Only, Battery Life: N/A, Driver Size: 50mm, Noise Cancellation: Passive Isolation, Charging Type: N/A", "15389.00", "18999.00", "19", "Audio", "/images/products/audio gear/hp4.jpg", 4.7, 1462, 144, "3-5 Days", false, true);
        seedProduct("Nova Orbit Max", "Resonance Orbit Max", "Resonance", "Premium luxury spatial audio headphones featuring magnetic earcups and reactive head-tracking technology. | Specs: Bluetooth Version: 5.4, Battery Life: 30 Hours, Driver Size: 40mm Dual-Diaphragm, Noise Cancellation: Smart Adaptive ANC (50dB), Charging Type: USB-C Fast Charge", "24999.00", "24999.00", "0", "Audio", "/images/products/audio gear/earbuds 1.jpg", 4.5, 2442, 76, "3-5 Days", true, false);
        seedProduct("Nova AeroBeat", "Pulse Audio AeroBeat", "Pulse Audio", "Durable neckband designed for workout sessions, featuring magnetic earbuds and fast pairing. | Specs: Bluetooth Version: 5.2, Battery Life: 24 Hours, Driver Size: 10mm, Noise Cancellation: Environmental Noise Cancellation (ENC), Charging Type: USB-C", "2149.00", "2499.00", "14", "Audio", "/images/products/audio gear/earbuds 2.jpg", 4.1, 985, 9, "Tomorrow", false, false);
        seedProduct("Nova SyncPods Elite", "EchoTech SyncPods Elite", "EchoTech", "Next-generation wireless earbuds with customised touch controls and low latency gaming mode. | Specs: Bluetooth Version: 5.3, Battery Life: 36 Hours, Driver Size: 12mm, Noise Cancellation: Smart ANC (42dB), Charging Type: Qi Wireless + USB-C", "4339.00", "6999.00", "38", "Audio", "/images/products/audio gear/earbuds 3.jpg", 4.2, 548, 9, "2 Days", false, false);
        seedProduct("Nova Soundstage Pro", "Resonance Soundstage Pro", "Resonance", "Premium TV soundbar with integrated subwoofers and cinematic Dolby Atmos support. | Specs: Bluetooth Version: 5.0 + HDMI eARC, Battery Life: AC Powered, Driver Size: Quad 3-inch + Dual Tweeters, Noise Cancellation: N/A, Charging Type: AC Power Cord", "16999.00", "16999.00", "0", "Audio", "/images/products/audio gear/speaker.jpg", 4.7, 2558, 2, "2 Days", false, true);
        seedProduct("Nova StreamCast Mic", "SonicX StreamCast Mic", "SonicX", "Professional cardioid condenser microphone with built-in pop filter and custom RGB gain dial. | Specs: Bluetooth Version: USB Connection, Battery Life: USB Powered, Driver Size: 16mm Condenser Capsule, Noise Cancellation: Real-time Noise Reduction, Charging Type: USB-C", "5039.00", "5999.00", "16", "Audio", "/images/products/audio gear/hp5.jpg", 4.7, 1706, 0, "2 Days", false, true);
        seedProduct("Nova EchoSphere Speaker", "EchoTech Sphere Speaker", "EchoTech", "Omnidirectional 360-degree smart home speaker with premium acoustic fabric and bass radiators. | Specs: Bluetooth Version: 5.3 + Wi-Fi, Battery Life: 15 Hours, Driver Size: 3.5-inch Woofer, Noise Cancellation: Room Correction, Charging Type: DC Adapter / USB-C", "6299.00", "8999.00", "30", "Audio", "/images/products/audio gear/speaker1.jpg", 4.5, 3302, 0, "Tomorrow", true, true);
        seedProduct("Nova RaveBox", "Pulse Audio RaveBox", "Pulse Audio", "Rugged outdoor waterproof Bluetooth speaker with dynamic synced LED rings. | Specs: Bluetooth Version: 5.3, Battery Life: 24 Hours, Driver Size: Dual 4-inch Woofers, Noise Cancellation: N/A, Charging Type: USB-C PD", "10439.00", "11999.00", "13", "Audio", "/images/products/audio gear/speaker2.jpg", 4.7, 2548, 98, "Within a week", false, false);
        seedProduct("Nova Monitor 5", "Resonance Monitor 5", "Resonance", "Active near-field reference monitors for music producers and video editors (sold as pair). | Specs: Bluetooth Version: TRS/XLR Balanced, Battery Life: AC Powered, Driver Size: 5.25-inch Kevlar, Noise Cancellation: N/A, Charging Type: Dual AC Power", "13199.00", "21999.00", "40", "Audio", "/images/products/audio gear/speaker3.jpg", 5.0, 2676, 46, "2 Days", false, true);
        seedProduct("Nova PurePods", "EchoTech PurePods", "EchoTech", "Comfort-first true wireless earbuds with touch interface and water-resistant nano coating. | Specs: Bluetooth Version: 5.2, Battery Life: 28 Hours, Driver Size: 10mm, Noise Cancellation: ENC for Calls, Charging Type: USB-C", "2719.00", "3999.00", "32", "Audio", "/images/products/audio gear/earbuds 4.jpg", 3.9, 820, 129, "3-5 Days", true, true);
        seedProduct("Nova AirFlow", "Pulse Audio AirFlow", "Pulse Audio", "Open-ear bone conduction headphones for safe outdoor athletics and ambient awareness. | Specs: Bluetooth Version: 5.3, Battery Life: 10 Hours, Driver Size: Bone Conduction, Noise Cancellation: Open-Ear Design, Charging Type: Magnetic Dock", "5499.00", "5499.00", "0", "Audio", "/images/products/audio gear/earbuds 5.jpg", 4.0, 1759, 170, "Within a week", false, true);
        seedProduct("Nova Clarity Bud", "SonicX Clarity Bud", "SonicX", "High-end earbuds featuring triple-mic voice pickup and advanced transparency mode. | Specs: Bluetooth Version: 5.4, Battery Life: 40 Hours, Driver Size: 11mm Dynamic, Noise Cancellation: Hybrid ANC (45dB), Charging Type: Qi Wireless + USB-C", "7649.00", "8499.00", "10", "Audio", "/images/products/audio gear/earbuds 6.jpg", 5.0, 3137, 40, "2 Days", false, true);
        seedProduct("Nova Symphony One", "Resonance Symphony One", "Resonance", "Premium over-ear headphones with custom carbon-fibre drivers and adaptive noise-cancelling engine. | Specs: Bluetooth Version: 5.3, Battery Life: 38 Hours, Driver Size: 40mm Carbon-fibre, Noise Cancellation: Adaptive ANC (46dB), Charging Type: USB-C", "6759.00", "12999.00", "48", "Audio", "/images/products/earbuds.png", 4.5, 1390, 140, "2 Days", false, false);
        seedProduct("Nova BeatBuds", "Pulse Audio BeatBuds", "Pulse Audio", "Affordable true wireless earbuds with deep bass booster and smart touch controls. | Specs: Bluetooth Version: 5.1, Battery Life: 20 Hours, Driver Size: 8mm, Noise Cancellation: Passive, Charging Type: USB-C", "1459.00", "1999.00", "27", "Audio", "/images/products/audio gear/earbuds.jpg", 4.6, 1518, 163, "2 Days", true, false);
        seedProduct("Nova Horizon Watch", "Chronos Horizon", "Chronos", "Elegant everyday smartwatch featuring a bright curved AMOLED display and detailed lifestyle tracking. | Specs: Display Type: 1.43-inch AMOLED, Battery Life: 14 Days, Water Resistance: 5ATM, Sensors: Heart Rate & SpO2, Compatibility: iOS & Android", "7999.00", "7999.00", "0", "Wearables", "/images/products/wearables/smartwatch.png", 4.5, 536, 57, "Within a week", false, true);
        seedProduct("Nova Apex Fit", "Apex Fit", "Apex", "Sleek fitness band optimised for activity logging, workout tracking, and posture notifications. | Specs: Display Type: 1.62-inch OLED, Battery Life: 10 Days, Water Resistance: IP68, Sensors: 6-Axis Motion Sensor, Compatibility: iOS & Android", "3499.00", "3499.00", "0", "Wearables", "/images/products/wearables/sw.jpg", 4.0, 767, 136, "3-5 Days", true, true);
        seedProduct("Nova Chronos X", "Chronos X", "Chronos", "Tactical rugged outdoor smartwatch built with sapphire glass and aerospace titanium. | Specs: Display Type: 1.5-inch Sapphire Glass, Battery Life: 7 Days, Water Resistance: 10ATM, Sensors: GPS & Altimeter, Compatibility: iOS & Android", "7820.00", "16999.00", "54", "Wearables", "/images/products/wearables/sw 1.jpg", 4.6, 988, 21, "Within a week", false, true);
        seedProduct("Nova Motion Pro", "Elevate Motion Pro", "Elevate", "Smart health tracker with active heart rate monitoring and guided breathing exercises. | Specs: Display Type: 1.78-inch LCD, Battery Life: 8 Days, Water Resistance: IP68, Sensors: Accelerometer, Compatibility: iOS & Android", "4499.00", "4499.00", "0", "Wearables", "/images/products/wearables/sw2.jpg", 4.4, 3055, 119, "Tomorrow", false, false);
        seedProduct("Nova Elevate Ultra", "Elevate Ultra", "Elevate", "Premium wellness watch equipped with advanced ECG measurement and skin temperature sensors. | Specs: Display Type: 1.4-inch Curved AMOLED, Battery Life: 12 Days, Water Resistance: 5ATM, Sensors: Blood Pressure & SpO2, Compatibility: iOS & Android", "12999.00", "12999.00", "0", "Wearables", "/images/products/wearables/sw3.jpg", 4.2, 100, 49, "Within a week", false, true);
        seedProduct("Nova Active Pulse", "Apex Active Pulse", "Apex", "Lightweight sports tracker band with automatic workout detection and daily step counter. | Specs: Display Type: 1.3-inch TFT, Battery Life: 5 Days, Water Resistance: IP67, Sensors: Sleep Tracker, Compatibility: iOS & Android", "1999.00", "1999.00", "0", "Wearables", "/images/products/wearables/sw4.jpg", 3.8, 163, 42, "Within a week", false, true);
        seedProduct("Nova Zenith Watch", "Zenith Watch", "Zenith", "Flagship lifestyle smartwatch with micro-bezel display, gesture controls, and standalone GPS. | Specs: Display Type: 1.43-inch AMOLED, Battery Life: 15 Days, Water Resistance: 5ATM, Sensors: Stress Tracker & Compass, Compatibility: iOS & Android", "7799.00", "9999.00", "22", "Wearables", "/images/products/wearables/sw5.jpg", 4.2, 1295, 188, "2 Days", false, false);
        seedProduct("Nova Aura Ring", "Aura Ring", "Aura", "Ultra-discreet smart ring crafted from titanium for continuous health, sleep, and HRV tracking. | Specs: Display Type: N/A (Smart Ring), Battery Life: 6 Days, Water Resistance: 50m, Sensors: Temp & HRV, Compatibility: iOS & Android", "13299.00", "18999.00", "30", "Wearables", "/images/products/wearables/smart ring.jpg", 5.0, 1280, 92, "2 Days", true, false);
        seedProduct("Nova FitBand Lite", "Apex FitBand Lite", "Apex", "Minimalist health band with sleep monitoring and phone notifications. | Specs: Display Type: 1.1-inch AMOLED, Battery Life: 20 Days, Water Resistance: 5ATM, Sensors: Optical Heart Rate, Compatibility: iOS & Android", "2499.00", "2499.00", "0", "Wearables", "/images/products/wearables/sw6.jpg", 3.9, 60, 165, "Tomorrow", false, true);
        seedProduct("Nova Aero Tracker", "Elevate Aero Tracker", "Elevate", "Stylish active watch with customised sports profiles and daily calories calculator. | Specs: Display Type: 1.39-inch AMOLED, Battery Life: 10 Days, Water Resistance: IP68, Sensors: Gyrometer, Compatibility: iOS & Android", "3899.00", "5999.00", "35", "Wearables", "/images/products/wearables/sw7.jpg", 3.9, 2232, 112, "Tomorrow", true, true);
        seedProduct("Nova Chronos Classic", "Chronos Classic", "Chronos", "Circular classic watch design with leather straps and smart activity widgets. | Specs: Display Type: 1.32-inch Circular LCD, Battery Life: 12 Days, Water Resistance: 3ATM, Sensors: Heart Rate, Compatibility: iOS & Android", "6999.00", "6999.00", "0", "Wearables", "/images/products/wearables/sw8.jpg", 4.3, 75, 47, "2 Days", false, true);
        seedProduct("Nova Horizon Lite", "Chronos Horizon Lite", "Chronos", "Budget-friendly smart companion with multiple watch faces and sedentary alerts. | Specs: Display Type: 1.69-inch TFT, Battery Life: 9 Days, Water Resistance: IP68, Sensors: Sleep & Heart Rate, Compatibility: iOS & Android", "2999.00", "2999.00", "0", "Wearables", "/images/products/wearables/sw9.jpg", 4.1, 3228, 111, "3-5 Days", false, false);
        seedProduct("Nova Luxe Smartwatch", "Zenith Luxe", "Zenith", "Ultimate luxury wearable with hand-polished ceramic finish and customised dials. | Specs: Display Type: 1.43-inch AMOLED Titanium, Battery Life: 5 Days, Water Resistance: 5ATM, Sensors: ECG & Stress, Compatibility: iOS & Android", "12979.00", "21999.00", "41", "Wearables", "/images/products/wearables/smartwatch.png", 4.4, 1468, 183, "Within a week", false, true);
        seedProduct("Nova Ring Pro", "Aura Ring Pro", "Aura", "Premium grade smart health ring with optimised battery and brushed gold finish. | Specs: Display Type: N/A (Titanium Ring), Battery Life: 7 Days, Water Resistance: 100m, Sensors: Core Temp & SpO2, Compatibility: iOS & Android", "23999.00", "23999.00", "0", "Wearables", "/images/products/wearables/tech ring.jpg", 4.6, 2323, 54, "3-5 Days", false, false);
        seedProduct("Nova Zenith Fit", "Zenith Fit", "Zenith", "Action smartwatch featuring track metrics navigation and elevation sensors. | Specs: Display Type: 1.4-inch AMOLED, Battery Life: 14 Days, Water Resistance: 5ATM, Sensors: GPS & Altimeter, Compatibility: iOS & Android", "11999.00", "11999.00", "0", "Wearables", "/images/products/wearables/sw.jpg", 4.6, 332, 2, "3-5 Days", false, false);
        seedProduct("Nova Phantom Controller", "Phantom Control X", "Phantom", "Wireless gamepad with Hall Effect joysticks and customisable mechanical action buttons. | Specs: Connectivity: 2.4GHz Wireless / BT / Wired, RGB Support: Yes (Custom Profile), Polling Rate: 250Hz, Battery: 10 Hours, Compatibility: PC / Xbox / Switch", "4999.00", "4999.00", "0", "Electronics", "/images/products/gaming/controller.jpg", 4.7, 3129, 37, "2 Days", false, false);
        seedProduct("Nova Titan RGB Keyboard", "Titan RGB Keyboard", "Titan", "Solid aluminium mechanical keyboard equipped with custom hot-swappable linear switches. | Specs: Connectivity: Wired USB-C, RGB Support: Per-Key RGB (16.8M colors), Polling Rate: 1000Hz, Battery: Wired, Compatibility: Windows / macOS", "7559.00", "11999.00", "37", "Electronics", "/images/products/gaming/keyboard.jpg", 4.9, 3477, 137, "3-5 Days", false, true);
        seedProduct("Nova Vortex Mouse", "Vortex Mouse", "Vortex", "Ergonomic gaming mouse featuring a high-performance 26K optical sensor and PTFE feet. | Specs: Connectivity: Lag-free Wireless / Wired, RGB Support: Dynamic Accent RGB, Polling Rate: 1000Hz, Battery: 60 Hours, Compatibility: Windows / macOS", "2580.00", "5999.00", "57", "Electronics", "/images/products/gaming/mouse.jpg", 4.7, 3192, 101, "Within a week", false, true);
        seedProduct("Nova Strike Elite Mouse", "Gladiator Strike Elite", "Gladiator", "Budget gaming mouse with durable switches and a lightweight honeycomb design. | Specs: Connectivity: Wired USB, RGB Support: Static RGB Strip, Polling Rate: 500Hz, Battery: Wired, Compatibility: Windows / macOS", "1999.00", "1999.00", "0", "Electronics", "/images/products/gaming/mouse1.jpg", 4.6, 2526, 5, "2 Days", false, false);
        seedProduct("Nova Velocity Pro Keyboard", "Titan Velocity Pro", "Titan", "Low-profile wireless mechanical keyboard with quiet tactile switches and travel cover. | Specs: Connectivity: Wireless 2.4GHz + BT, RGB Support: RGB Backlit, Polling Rate: 1000Hz, Battery: 120 Hours (RGB Off), Compatibility: Windows / macOS / Android", "7919.00", "8999.00", "12", "Electronics", "/images/products/gaming/keyboard1.jpg", 4.4, 3401, 29, "Within a week", false, false);
        seedProduct("Nova Arena Hub Controller", "Phantom Arena Hub", "Phantom", "Pro controller featuring rear remappable paddles and adjustable trigger stops. | Specs: Connectivity: Wired USB-C, RGB Support: Halo Ring RGB, Polling Rate: 500Hz, Battery: Wired, Compatibility: PC / PS5 / Xbox", "2940.00", "6999.00", "58", "Electronics", "/images/products/gaming/controller1.jpg", 4.7, 1910, 0, "2 Days", false, false);
        seedProduct("Nova CyberKeys K75", "Aegis CyberKeys K75", "Aegis", "Gasket-mounted 75% mechanical keyboard with retro keycaps and linear silent switches. | Specs: Connectivity: Wireless 2.4GHz & BT, RGB Support: Per-key RGB, Polling Rate: 1000Hz, Battery: 80 Hours, Compatibility: Windows / macOS / iOS", "4100.00", "9999.00", "59", "Electronics", "/images/products/gaming/keyboard2.jpg", 4.4, 3161, 0, "Tomorrow", false, true);
        seedProduct("Nova HyperGlide Mouse", "Vortex HyperGlide", "Vortex", "Ultra-lightweight gaming mouse weighing only 58g for fast reflexes and FPS games. | Specs: Connectivity: 2.4GHz Wireless, RGB Support: Logo Accent, Polling Rate: 1000Hz, Battery: 50 Hours, Compatibility: Windows / macOS", "5524.00", "6499.00", "15", "Electronics", "/images/products/gaming/mouse2.jpg", 5.0, 2016, 178, "Within a week", false, false);
        seedProduct("Nova ErgoSplit Keyboard", "Aegis ErgoSplit", "Aegis", "Split mechanical keyboard for ergonomic gaming and long-session typing comfort. | Specs: Connectivity: Split Type-C / Wireless, RGB Support: Underglow RGB, Polling Rate: 1000Hz, Battery: 100 Hours, Compatibility: Windows / macOS / Linux", "14999.00", "14999.00", "0", "Electronics", "/images/products/gaming/keyboard3.jpg", 4.1, 2803, 3, "3-5 Days", false, false);
        seedProduct("Nova Apex Control Pad", "Gladiator Control Pad", "Gladiator", "Mobile gaming controller with telescopic design and mechanical switches. | Specs: Connectivity: Bluetooth 5.1 / Wired, RGB Support: Dual-zone RGB, Polling Rate: 250Hz, Battery: 12 Hours, Compatibility: PC / Mobile / Switch", "1760.00", "3999.00", "56", "Electronics", "/images/products/gaming/controller2.jpg", 4.6, 2519, 196, "2 Days", false, true);
        seedProduct("Nova Aegis Gaming Headset", "Aegis Gaming Headset", "Aegis", "Wireless gaming headset with 7.1 spatial surround audio and a retractable mic. | Specs: Connectivity: 2.4GHz Wireless / 3.5mm, RGB Support: Earcap LED, Polling Rate: N/A, Battery: 30 Hours, Compatibility: PC / PS5 / Switch", "6959.00", "7999.00", "13", "Electronics", "/images/products/gaming/gaming headset.jpg", 4.2, 2998, 165, "Within a week", false, true);
        seedProduct("Nova SpectraVision 27", "Titan SpectraVision 27", "Titan", "27-inch IPS gaming monitor with 165Hz refresh rate and ultra-thin bezels. | Specs: Connectivity: DisplayPort / Dual HDMI / USB-C, RGB Support: Rear Ambient Glow, Polling Rate: 165Hz Refresh Rate, Battery: AC Powered, Compatibility: PC / Consoles", "17799.00", "19999.00", "11", "Electronics", "/images/products/monitor.png", 4.2, 3212, 76, "3-5 Days", true, false);
        seedProduct("Nova Phantom Mouse", "Phantom Mouse Pro", "Phantom", "Ambidextrous wireless gaming mouse featuring mechanical switch customisation. | Specs: Connectivity: Ultra-light Wireless, RGB Support: Minimalist RGB, Polling Rate: 2000Hz, Battery: 45 Hours, Compatibility: Windows / macOS", "3024.00", "5499.00", "45", "Electronics", "/images/products/gaming/mouse3.jpg", 4.0, 1889, 136, "Tomorrow", false, false);
        seedProduct("Nova Strike Mechanical", "Gladiator Strike Mechanical", "Gladiator", "Entry-level mechanical keyboard with blue clicky switches and double-shot keycaps. | Specs: Connectivity: Wired, RGB Support: Rainbow Backlit, Polling Rate: 1000Hz, Battery: Wired, Compatibility: Windows / macOS", "3999.00", "3999.00", "0", "Electronics", "/images/products/gaming/keyboard4.jpg", 4.5, 1236, 143, "2 Days", true, false);
        seedProduct("Nova Gladiator Arcade", "Gladiator Arcade", "Gladiator", "Classic arcade fightstick featuring authentic Sanwa parts and customisable template. | Specs: Connectivity: USB Wired, RGB Support: Button LED Rings, Polling Rate: 1000Hz, Battery: Wired, Compatibility: PC / PS4 / Switch", "8999.00", "8999.00", "0", "Electronics", "/images/products/gaming/gaming-controller.png", 4.5, 645, 82, "2 Days", true, false);
        seedProduct("Nova Home Core Hub", "Core Home Hub", "Core", "Central smart home hub connecting all Zigbee and Thread smart devices locally. | Specs: Connectivity: Wi-Fi 6, Zigbee, Thread, Smart Assistant Support: Google Assistant & Alexa, Power Usage: 15W, Range: Up to 1500 sq ft", "5159.00", "5999.00", "14", "Smart Home", "/images/products/smart-device/Central smart home hub connecting all Zigbee and Thread smart devices locally..jpg", 4.0, 1431, 178, "Within a week", false, true);
        seedProduct("Nova Lumina Lightstrip", "Lumina Lightstrip", "Lumina", "Smart flexible lightstrip offering 16 million colours with dynamic audio sync. | Specs: Connectivity: Wi-Fi 2.4GHz, Smart Assistant Support: Google & Alexa, Power Usage: 24W, Range: Smart Cloud Control", "1524.00", "2499.00", "39", "Smart Home", "/images/products/smart-device/Smart flexible lightstrip offering 16 million colours with dynamic audio sync..jpg", 3.9, 3433, 63, "Tomorrow", false, false);
        seedProduct("Nova Guardian Cam", "Guardian Cam", "Guardian", "Indoor 2K security camera with intelligent AI detection and pan-tilt rotation. | Specs: Connectivity: Wi-Fi 2.4GHz / 5GHz, Smart Assistant Support: Alexa & Google Assistant, Power Usage: 5W (USB Powered), Range: 30ft Night Vision", "2479.00", "3999.00", "38", "Smart Home", "/images/products/smart-device/Nova Guardian Cam.jpg", 5.0, 2033, 163, "Within a week", false, true);
        seedProduct("Nova Sense Mini Sensor", "Sense Mini Sensor", "Sense", "Compact motion sensor detecting movement up to 7 metres with 170-degree range. | Specs: Connectivity: Zigbee 3.0, Smart Assistant Support: SmartHub Integrated, Power Usage: CR2032 Battery, Range: 80ft to Hub", "1299.00", "1299.00", "0", "Smart Home", "/images/products/smart-device/Precision temperature and humidity sensor triggering automatic HVAC rules..jpg", 4.6, 1874, 4, "2 Days", true, true);
        seedProduct("Nova Smart Plug Pro", "Nexus Smart Plug Pro", "Nexus", "Compact smart plug with power consumption monitoring and scheduled timers. | Specs: Connectivity: Wi-Fi 2.4GHz, Smart Assistant Support: Alexa & Google, Power Usage: Max 10A / 1200W, Range: Smart Cloud Control", "1229.00", "1499.00", "18", "Smart Home", "/images/products/smart-device/Compact smart plug with power consumption monitoring and scheduled timers..jpg", 4.3, 3045, 137, "3-5 Days", false, true);
        seedProduct("Nova Guardian Cam Outdoor", "Guardian Cam Outdoor", "Guardian", "Weather-proof wireless outdoor camera with rechargeable battery and solar panel support. | Specs: Connectivity: Wi-Fi + Rechargeable Battery, Smart Assistant Support: Alexa & Google, Power Usage: Internal Battery (6 Months), Range: 50ft Night Vision", "3150.00", "6999.00", "55", "Smart Home", "/images/products/smart-device/Weather-proof wireless outdoor camera with rechargeable battery and solar panel support..jpg", 4.2, 868, 52, "Within a week", false, false);
        seedProduct("Nova Lumina Smart Bulb", "Lumina Smart Bulb", "Lumina", "Smart LED bulb with colour temperature controls and custom lighting scenes. | Specs: Connectivity: Bluetooth & Wi-Fi, Smart Assistant Support: Google & Alexa, Power Usage: 9W (60W Equiv), Range: Smart Cloud Control", "999.00", "999.00", "0", "Smart Home", "/images/products/lumina-sync.jpg", 4.7, 897, 120, "3-5 Days", false, false);
        seedProduct("Nova Sense Temp Sensor", "Sense Temp Sensor", "Sense", "Precision temperature and humidity sensor triggering automatic HVAC rules. | Specs: Connectivity: Bluetooth LE / Zigbee, Smart Assistant Support: Home Core Compatible, Power Usage: CR2450 Battery, Range: 100ft", "1199.00", "1199.00", "0", "Smart Home", "/images/products/smart-device/Precision temperature and humidity sensor triggering automatic HVAC rules..jpg", 4.6, 1650, 108, "3-5 Days", false, true);
        seedProduct("Nova Smart Thermostat", "Core Smart Thermostat", "Core", "Intelligent thermostat featuring automatic schedule learning and geofencing. | Specs: Connectivity: Wi-Fi 2.4GHz, Smart Assistant Support: Alexa & Google, Power Usage: 24V C-Wire, Range: Smart Cloud Control", "14999.00", "14999.00", "0", "Smart Home", "/images/products/smart-device/Intelligent thermostat featuring automatic schedule learning and geofencing..jpg", 4.4, 3371, 68, "3-5 Days", false, false);
        seedProduct("Nova Smart Lock Pro", "Guardian Smart Lock Pro", "Guardian", "Retrofit smart lock supporting keyless entry, codes, and fingerprint access. | Specs: Connectivity: Wi-Fi & Bluetooth, Smart Assistant Support: Alexa & Google, Power Usage: 4 AA Batteries, Range: Bluetooth range / Cloud", "11699.00", "12999.00", "10", "Smart Home", "/images/products/smart-device/Retrofit smart lock supporting keyless entry, codes, and fingerprint access..jpg", 4.7, 273, 145, "3-5 Days", false, false);
        seedProduct("Nova Guardian Video Doorbell", "Guardian Video Doorbell", "Guardian", "Smart doorbell featuring two-way audio, custom quick replies, and human detection. | Specs: Connectivity: Wi-Fi 2.4GHz, Smart Assistant Support: Alexa & Google, Power Usage: Hardwired / Battery, Range: 30ft Motion Detection", "7019.00", "8999.00", "22", "Smart Home", "/images/products/smart-device/Smart doorbell featuring two-way audio, custom quick replies, and human detection..jpg", 4.7, 2412, 3, "2 Days", true, true);
        seedProduct("Nova Lumina Ceiling Panel", "Lumina Ceiling Panel", "Lumina", "Modern flush-mount ambient smart ceiling panel with adjustable white tones. | Specs: Connectivity: Wi-Fi 2.4GHz, Smart Assistant Support: Alexa & Google, Power Usage: 36W, Range: Dynamic Room Coverage", "4479.00", "7999.00", "44", "Smart Home", "/images/products/smart-device/Modern flush-mount ambient smart ceiling panel with adjustable white tones..jpg", 4.4, 3335, 139, "Within a week", false, true);
        seedProduct("Nova Flow Water Valve", "Nexus Flow Water Valve", "Nexus", "Smart water main shutoff valve controller with automated leak detection routines. | Specs: Connectivity: Zigbee / Wi-Fi, Smart Assistant Support: Alexa & Google, Power Usage: 12V DC Adapter, Range: 120ft to Hub", "4700.00", "9999.00", "53", "Smart Home", "/images/products/smart-device/Smart water main shutoff valve controller with automated leak detection routines..jpg", 4.5, 904, 7, "Tomorrow", false, false);
        seedProduct("Nova Aura Humidifier", "Core Humidifier", "Core", "Smart ultrasonic humidifier with adjustable mist settings and essential oil tray. | Specs: Connectivity: Wi-Fi 2.4GHz, Smart Assistant Support: Alexa & Google, Power Usage: 30W, Range: Up to 350 sq ft", "2500.00", "4999.00", "50", "Smart Home", "/images/products/smart-device/Smart ultrasonic humidifier with adjustable mist settings and essential oil tray..jpg", 3.9, 3203, 4, "Tomorrow", false, true);
        seedProduct("Nova Guard Smoke Detector", "Guardian Smoke Detector", "Guardian", "Interlinked smart smoke and carbon monoxide detector sending real-time alerts. | Specs: Connectivity: Wi-Fi / Interlinked, Smart Assistant Support: Phone Alerts, Power Usage: 10-Year Lithium Battery, Range: Whole-House Interlink", "3499.00", "3499.00", "0", "Smart Home", "/images/products/smart-device/smoke detecotr.jpg", 4.3, 1139, 124, "3-5 Days", false, true);
        seedProduct("Nova Charge 65", "ChargeFlow 65W", "ChargeFlow", "Ultra-compact GaN fast wall charger with dual USB-C ports and power distribution. | Specs: Wattage: 65W GaN Fast Charge, Cable Length: N/A, Material: Fireproof PC, Charging Standard: PD 3.0 / QC 4.0 / PPS", "2999.00", "2999.00", "0", "Accessories", "/images/products/accessories/charger4.jpg", 4.5, 1033, 142, "3-5 Days", true, true);
        seedProduct("Nova FlexLink Cable", "FlexLink USB-C", "FlexLink", "Double-braided high durability nylon USB-C to USB-C charging and data cable. | Specs: Wattage: 100W USB-C PD, Cable Length: 2 Metres (6.6 ft), Material: Double-Braided Premium Nylon, Charging Standard: USB 2.0 / PD 3.0", "719.00", "999.00", "28", "Accessories", "/images/products/accessories/cable.jpg", 3.9, 1307, 9, "2 Days", false, false);
        seedProduct("Nova PowerVault 10K", "PowerVault 10K", "PowerVault", "Slim aluminium power bank featuring 22.5W fast charging and dual output. | Specs: Wattage: 22.5W Output / 18W Input, Cable Length: 0.3m Cable Included, Material: Brushed Aluminium, Charging Standard: PD 3.0 & QC 3.0", "1219.00", "1999.00", "39", "Accessories", "/images/products/accessories/powerbank.png", 4.0, 2159, 113, "Tomorrow", true, true);
        seedProduct("Nova Dock Pro", "DockPro 8-in-1", "DockPro", "8-in-1 USB-C docking station with 4K HDMI, SD card reader, and Power Delivery. | Specs: Wattage: 85W Pass-Through Charging, Cable Length: 0.5m Host Cable, Material: Anodised Aluminium, Charging Standard: Thunderbolt 3 / USB-C", "2640.00", "5999.00", "56", "Accessories", "/images/products/accessories/8in1 docking station.jpg", 4.6, 1146, 0, "Within a week", true, true);
        seedProduct("Nova AirStand Qi", "ChargeFlow AirStand Qi", "ChargeFlow", "Fast wireless charging stand featuring dual coil design for vertical/horizontal phone charging. | Specs: Wattage: 15W Wireless Fast Charge, Cable Length: 1.5m Cable included, Material: Zinc Alloy + Premium Fabric, Charging Standard: Qi Wireless Standard", "2134.00", "3499.00", "39", "Accessories", "/images/products/accessories/5in 1 charger.jpg", 4.9, 3387, 8, "Within a week", false, true);
        seedProduct("Nova PowerVault 20K", "PowerVault 20K", "PowerVault", "High capacity 20,000mAh laptop power bank with 45W USB-C Power Delivery. | Specs: Wattage: 45W Power Delivery, Cable Length: 0.5m USB-C Cable, Material: Polycarbonate, Charging Standard: PD 3.0 & QC 4.0", "2159.00", "3999.00", "46", "Accessories", "/images/products/accessories/powervault.jpg", 4.1, 504, 148, "3-5 Days", true, false);
        seedProduct("Nova Charge 100 GaN", "ChargeFlow 100 GaN", "ChargeFlow", "Quad-port GaN wall charger supporting multi-device charging up to 100W. | Specs: Wattage: 100W Quad-Port GaN, Cable Length: N/A, Material: Premium ABS, Charging Standard: PD 3.0 / QC 3.0 / PPS", "4049.00", "4999.00", "19", "Accessories", "/images/products/accessories/charger5.jpg", 4.8, 968, 151, "3-5 Days", false, true);
        seedProduct("Nova BaseStation Stand", "MultiLink BaseStation", "MultiLink", "3-in-1 premium charging stand for phone, smartwatch, and wireless earbuds. | Specs: Wattage: 15W Wireless Stand + 5W Watch, Cable Length: 1.5m Adapter, Material: Aluminium + Leather, Charging Standard: Qi Dual Charger", "7999.00", "7999.00", "0", "Accessories", "/images/products/accessories/3-in-1 premium charging stand for phone, smartwatch, and wireless earbuds.'.jpg", 4.0, 474, 114, "Within a week", true, false);
        seedProduct("Nova FlexLink Micro", "FlexLink Micro", "FlexLink", "Highly durable braided USB-A to Micro-USB cable for legacy device sync. | Specs: Wattage: 15W Charging, Cable Length: 1 Metre, Material: Braided Nylon, Charging Standard: USB-A to Micro-USB", "404.00", "499.00", "19", "Accessories", "/images/products/accessories/cable1.jpg", 3.9, 2375, 180, "3-5 Days", false, false);
        seedProduct("Nova MagMount Car", "ChargeFlow MagMount Car", "ChargeFlow", "Magnetic air-vent car mount with integrated 15W wireless fast charger. | Specs: Wattage: 15W MagSafe Wireless, Cable Length: 1.2m Charger, Material: ABS + Carbon Fibre, Charging Standard: Qi / MagSafe Compatible", "1559.00", "2999.00", "48", "Accessories", "/images/products/accessories/Magnetic air-vent car mount with integrated 15W wireless fast charger..jpg", 4.7, 60, 4, "Tomorrow", false, false);
        seedProduct("Nova Charge Duo 35W", "ChargeFlow Duo 35W", "ChargeFlow", "Dual USB-C wall charger with smart power allocation in a pocketable format. | Specs: Wattage: 35W Dual Port USB-C, Cable Length: N/A, Material: Matte Finish PC, Charging Standard: PD 3.0 / PPS", "1999.00", "1999.00", "0", "Accessories", "/images/products/accessories/multiport charger.jpg", 5.0, 82, 105, "3-5 Days", false, false);
        seedProduct("Nova FlexLink Lightning", "FlexLink Lightning", "FlexLink", "Premium braided USB-C to Apple Lightning cable with MFi certification. | Specs: Wattage: 27W Fast Charging, Cable Length: 1.2 Metres, Material: Braided Nylon, Charging Standard: MFi Apple Lightning", "1299.00", "1299.00", "0", "Accessories", "/images/products/accessories/cable 2.jpg", 4.5, 3094, 127, "2 Days", false, true);
        seedProduct("Nova Travel Charge Hub", "MultiLink Travel Hub", "MultiLink", "Universal international travel adapter with built-in multi-port USB charger. | Specs: Wattage: 45W Multi-Port Travel Adapter, Cable Length: N/A, Material: Fire-Retardant ABS, Charging Standard: US/UK/EU Universal Pins", "3009.00", "3499.00", "14", "Accessories", "/images/products/accessories/8in1 docking station.jpg", 4.2, 2914, 10, "2 Days", true, true);
        seedProduct("Nova DeskMat Ambient", "ChargeFlow DeskMat Ambient", "ChargeFlow", "Felt desk mat with an integrated 10W wireless charging zone for accessories. | Specs: Wattage: 10W Wireless Charging zone, Cable Length: 1.8m Braided Cable, Material: Water-Resistant Felt + Leather, Charging Standard: Qi Wireless", "4499.00", "4499.00", "0", "Accessories", "/images/products/accessories/deskmat ambient.jpg", 4.3, 2681, 67, "2 Days", false, false);
        seedProduct("Nova PowerVault Mini", "PowerVault Mini", "PowerVault", "Keychain-sized emergency mini power bank with integrated USB-C connector. | Specs: Wattage: 12W output, Cable Length: Integrated USB-C Connector, Material: ABS Plastic, Charging Standard: Standard 5V/2.4A", "1199.00", "1199.00", "0", "Accessories", "/images/products/accessories/High capacity 20,000mAh laptop power bank with 45W USB-C Power Delivery..jpg", 4.5, 675, 5, "Within a week", false, true);
        seedProduct("Nova MultiLink Hub 5-in-1", "MultiLink Hub 5-in-1", "MultiLink", "5-in-1 USB-C hub with 4K HDMI, triple USB-A ports, and pass-through power. | Specs: Wattage: 60W Power Delivery, Cable Length: 0.15m Integrated Cable, Material: Aluminium Shell, Charging Standard: USB-C Hub", "2499.00", "2499.00", "0", "Accessories", "/images/products/accessories/8in1 docking station.jpg", 4.1, 2187, 124, "Within a week", false, false);
        seedProduct("Nova Charge 20W Mini", "ChargeFlow 20W Mini", "ChargeFlow", "Ultra mini fast wall charger designed for phones and accessories. | Specs: Wattage: 20W Fast Charger, Cable Length: N/A, Material: Flame-Resistant PC, Charging Standard: Power Delivery 3.0", "1019.00", "1199.00", "15", "Accessories", "/images/products/accessories/usb-charger.png", 4.2, 424, 128, "3-5 Days", false, false);

    }

    private void seedProduct(String oldName, String name, String brand, String desc, String price, String originalPrice, String discount, String cat, String img, double rating, int reviewCount, int stock, String deliveryEstimate, boolean isBestSeller, boolean isFreeDelivery) {
        Optional<Product> existing = productRepository.findAll().stream()
                .filter(p -> p.getName().equals(name) || p.getName().equals(oldName))
                .findFirst();

        if (existing.isEmpty()) {
            Product product = new Product();
            product.setName(name);
            product.setDescription(desc);
            product.setPrice(new BigDecimal(price));
            product.setOriginalPrice(new BigDecimal(originalPrice));
            product.setDiscount(new BigDecimal(discount));
            product.setStock(stock);
            product.setCategory(cat);
            product.setImageUrl(img);
            product.setBrand(brand);
            product.setRating(rating);
            product.setReviewCount(reviewCount);
            product.setDeliveryEstimate(deliveryEstimate);
            product.setIsBestSeller(isBestSeller);
            product.setIsFreeDelivery(isFreeDelivery);
            productRepository.save(product);
            System.out.println("Created new NOVA product: " + name);
        } else {
            Product product = existing.get();
            if (true) { // Force update all products with new fields
                product.setName(name);
                product.setImageUrl(img);
                product.setBrand(brand);
                product.setRating(rating);
                product.setPrice(new BigDecimal(price));
                product.setOriginalPrice(new BigDecimal(originalPrice));
                product.setDiscount(new BigDecimal(discount));
                product.setReviewCount(reviewCount);
                product.setStock(stock);
                product.setDeliveryEstimate(deliveryEstimate);
                product.setIsBestSeller(isBestSeller);
                product.setIsFreeDelivery(isFreeDelivery);
                productRepository.save(product);
                System.out.println("Updated product: " + name);
            }
        }
    }
}
